services:
  ecommerce_mongodb:
    image: mongo:8.0
    container_name: ecommerce_mongodb
    ports:
      - "${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
    volumes:
      - mongodb_data:/data/db

  ecommerce_minio:
    image: minio/minio:latest
    container_name: ecommerce_minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_API_PORT:-9000}:${MINIO_API_PORT:-9000}"
      - "${MINIO_WEB_PORT:-9001}:${MINIO_WEB_PORT:-9001}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-root}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-indomiegorengoriginal}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-indomiegorengoriginal}
    volumes:
      - minio_data:/data

  ecommerce_restapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_restapi
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      .env
    depends_on:
      - ecommerce_mongodb
      - ecommerce_minio

volumes:
  mongodb_data:
  minio_data:
